version: '3.8'

services:
  king-21:
    image: david-21
    build: .
    ports:
      - '7004:3000'
    environment:
      - MONGODB_URI:'mongodb://mongo:27017/Afrid'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
